### PR TITLE
Fixes and improvements

### PR DESCRIPTION
**Pull request by thomasf**
Great idea! I've been wanting to write this myself.. 

This change mostly fixes issues I got when I used this package but there are some behavior changes as well.

Please check this out and get back to me if you have any comments or questions before possibly merging.

### CODE REVIEW

**Comment by thomasf** [comment]
I kind of rushed through these changes but I've been using my version all day without problems.

At first I tried to do this in multiple branches but it became too much work to handle that situation.

I got some strange problems because the org-src edit functions were called from inside this package,  the changed version currently ignores default org source block indent config.

**Comment by lujun9972** [comment]
glad that you like this package and thank you for the fixing.
would you mind to descripe that strang problem? because it seems ok to me.

**Comment by thomasf** [comment]
Mostly it messed up window/buffer/point locations .. putting save-excursion around those parts did not help at all. I'm not mistaken those functions are only supposed to be used interactively.

**Comment by thomasf** [comment]
@lujun9972  Ah, good note about the makefiles. Will have to make it conditional or something then. What caused me to do that in the first place was that I got irregular indentation in some snippets, I still think that it's a valid thing to do generally to avoid mixing too much stuff by normalising indentation, right?

**Comment by thomasf** [comment]
So, i fixed the easy part, the with-buffer thing. 

Do you think that implementing this defcusom be enough to get this merged? (something like that)

``` el
(defcustom code-library-use-tabs '(makefile-mode)
  "List of modes which will be retabified.

Normally code-library removed tabs to normalise indentation
because code can come from a range of sources where the
formatting and buffer local tab width can be in use."
  :group 'code-library)
```

**Comment by thomasf** [comment]
I just pushed a rebase of all previous changes again with a fix for the temp-buffer thing and added a new commit with a defcustom like the one above.. I also modified so that the whole buffer will be snipped if there isnt a region and point isn't on a defun.

In the defcustom we could support a value of `t` instead of a list which would mean to always keep indentation but I think it's a bad idea because the original tab-width is lost inside the org-mode documents.

**Comment by lujun9972** [comment]
How about indent the code this way:
1. make the temp buffer the same major mode as the origin buffer
2. call the `indent-according-to-mode' function to indent the code

Do you think this will be work?

**Comment by thomasf** [comment]
I don't trust that all modes can do that correctly. It will usually work but when it doesn't it gets very messy. I don't think it will do what we want it to either.

**Comment by thomasf** [comment]
What caused me to start doing the untabify to begin with was that I was adding code snippets from several javascript projects with different editorconfig files.. some of the snippets just looked really strange at places.

Also,  `(setq org-src-tab-acts-natively t)` doesnt always seem to work as expected. When I snipped the makefile just to test it just recently the snippet inside of org-mode had tab width set to 2 while it's 4 in the normal makefile-mode.

**Comment by lujun9972** [comment]
I have tried this code with some makefile snippets, but It seems the untabify thing still work and I don't know why....

**Comment by thomasf** [comment]
Ok, I'll double check it agin.

**Comment by lujun9972** [comment]
I will merge it first, thank you

**Comment by thomasf** [comment]
which make-file-mode were you using.. I only added two of them..

**Comment by lujun9972** [comment]
I tried makefile-mode and makefile-gmake-mode.

**Comment by thomasf** [comment]
I can't reproduce the problem,,.

Looks good here except the difference of tab-width.

image

**Comment by lujun9972** [comment]
That's wired. I will check it later. now I have to go for work

**Comment by lujun9972** [comment]
Hi, what's the default value of indent-tabs-mode in your emacs config?

**Comment by thomasf** [comment]
Hi again, it's off... `(setq-default  indent-tabs-mode nil  tab-width 4)`

**Comment by lujun9972** [comment]
It looks problem occur  in the tangle stage.
Maybe we should add some additional header arguments

**Pull request merged**
