### PR TITLE
WIP Add defcustom for lower case org mode keywords

### PR DESCRIPTION
**Pull request by thomasf**
I know it's not the default org mode way but to me it looks infinitely better muting these a bit.
I left the defaults as is.

### CODE REVIEW

**Comment by lujun9972** [comment]
How about implement this way:

(defcustom code-library-keyword-format-function 'identity
  "This function will be used to format the org keyword.")

(defun code-library-create-snippet (head &optional keep-indent)
  "Create and return a new org heading with source block.

HEAD is the org mode heading"
  (let ((content (code-library-get-thing keep-indent))
        (code-major-mode (replace-regexp-in-string "-mode$" "" (symbol-name major-mode)))
        (tangle-file (if (buffer-file-name) (file-name-nondirectory (buffer-file-name)))))
    (with-temp-buffer
      (insert content)
      (org-escape-code-in-region (point-min) (point-max))
      (unless (bolp)
        (insert "\n"))
      (insert (format "#+%s\n" (funcall code-library-keyword-format-function "END_SRC")))
      (goto-char (point-min))
      (insert (format "\* %s\n" head))
      (insert (format "#+%s %s" (funcall code-library-keyword-format-function "BEGIN_SRC") code-major-mode))
      (when tangle-file
        (insert (format " :%s %s" (funcall code-library-keyword-format-function "tangle") tangle-file)))
      (insert "\n")
      (buffer-string))))

**Comment by thomasf** [comment]
That looks a bit nicer.. I was actually beginning with something like that but I went for the more specific use case simple boolean setting because I wasn't sure how big the risk of the need for changes which breaks end user configurations would become..

Regardless of the the defcustom case I probably reverted too far back by removing my  `code-library-format-org-keyword` function as well. It sure does make the code much more readable.

**Comment by lujun9972** [comment]
I am sorry, I'm not that good at English.
What you mean "I probably reverted too far back by removing my code-library-format-org-keyword function as well." 
 I can't see where is the code-library-format-org-keyword function.

**Comment by thomasf** [comment]
Sorry for being unclear.

I had a `code-library-format-org-keyword` function earlier but I removed it before creating this pull request. I'll update this pull request soon.

**Pull request closed without merging**
